DOCSP-15886 doc limitations with shared clusters
mongodb/docs-commandline-tools pull request #124
Opened 2024-02-08 22:31 UTC by kanchana-mongodb

## DESCRIPTION
Adds documentation for mongodump and mongorestore limitations with free and shared Atlas clusters

## STAGING

## JIRA
https://jira.mongodb.org/browse/DOCS-15886

## BUILD LOG

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-02-09 15:25 UTC, ajhuh-mdb approved these changes
LGTM % one suggestion

2024-02-09 15:25 UTC, ajhuh-mdb commented on source/mongodump.txt
> +Using ``mongodump`` on Atlas Cluster
[suggestion] This applies to the mongorestore page, too, but for grammar, I think we either want to drop "cluster," make it plural into "Atlas Clusters," or add "an" before "Atlas Cluster".

```suggestion
Using ``mongodump`` on Atlas Clusters 
```

2024-02-09 15:25 UTC, ajhuh-mdb commented on source/mongorestore.txt
> +Using ``mongorestore`` on Atlas Cluster
Same suggestion as above

2024-02-13 20:57 UTC, rohshar commented on source/mongodump.txt
> +Using ``mongodump`` on Atlas Clusters
This title should probably say Atlas free and shared tier clusters

2024-02-13 20:57 UTC, rohshar commented on source/mongorestore.txt
> +- You can't run ``mongorestore`` on the ``admin`` database. If you use
I think it should also mention that it is skipped by default (if db unspecified) on these clusters

2024-02-14 18:07 UTC, rohshar requested changes

2024-02-14 18:07 UTC, rohshar commented on source/mongorestore.txt
> +  ``mongorestore`` skips this option.
```suggestion
  ``mongorestore`` skips this database.
```

2024-02-14 18:07 UTC, rohshar commented on source/mongorestore.txt
> +  ``mongorestore`` skips this option.
I would also add this sentence above the previous one.

Also, I think that you should add a similar sentence to the mongodump section

2024-02-14 19:36 UTC, rohshar approved these changes

2024-02-15 18:07 UTC, merged