DOCS-15555 mongorestore fails to copy/clone an existing database to a new one
mongodb/docs-commandline-tools pull request #125
Opened 2024-02-09 16:43 UTC by kanchana-mongodb

## DESCRIPTION
Looks like mongorestore fails to copy/clone an existing database to a new one on Windows if nsfrom and nsTo values are inside single quotes; only double quotes work on windows. In my testing, double quotes work on mac too. Instead of documenting the right type of quotes to use for each OS, I replaced the quotes in the examples so it will work on mac and windows.

## STAGING
https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCS-15555/

## JIRA
https://jira.mongodb.org/browse/DOCS-15555

## BUILD LOG
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c655956b2f17c95a916fc2

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-02-09 17:30 UTC, jocelyn-mendez1 approved these changes
Thanks for these updates @kanchana-mongodb, this LGTM!

2024-02-13 20:43 UTC, tfogo requested changes

2024-02-13 20:43 UTC, tfogo commented on source/includes/extracts-clone-copy-db-examples.yaml
> +         mongorestore --archive="mongodump-test-db" --nsFrom="test.*" --nsTo="examples.*'"
There's `'` that should have been deleted at the end here.

2024-02-15 21:07 UTC, tfogo requested changes
Sorry, noticed something else. Looks good once that's fixed.

2024-02-22 20:21 UTC, merged