(DOCSP-39188): Clarify that restores can be at most one major version ahead
mongodb/docs-commandline-tools pull request #150
Opened 2024-05-03 20:19 UTC by jeff-allen-mongo

## DESCRIPTION

Clarify that restores can be at most one major version ahead

## STAGING

- [mongorestore](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-39188/mongorestore/)
- [mongodump](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-39188/mongodump/#definition)
- [mongorestore Behavior](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-39188/mongorestore/mongorestore-behavior-access-usage/#restore-to-matching-server-version)
- [mongodump Behavior](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-39188/mongodump/mongodump-behavior/#restore-to-matching-server-version)

## JIRA

## BUILD LOG

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-05-06 14:20 UTC, jmd-mongo approved these changes
Thanks for these updates, @jeff-allen-mongo! This one LGTM.

Thanks,
Joe

2024-05-06 15:19 UTC, mvankeulen94 requested changes
Apologies for the confusion. The issue I'd like to solve for is to make sure that users know where our recommended upgrade procedures are. The BSON claims currently being made aren't wrong, but we don't want users to be tempted to try to use dump and restore as a way to circumvent our standard upgrade procedures. Thanks!

2024-05-06 17:45 UTC, jeff-allen-mongo reviewed
@mvankeulen94 thanks for the feedback! I adjusted the copy to focus more on clarifying that dump / restore should not be used to upgrade a deployment. Could you take another look?

2024-05-06 20:02 UTC, mvankeulen94 requested changes
Just a couple minor wording changes, thanks!
I'll also flag this to TAR engineering & TS so they're aware that these changes are being made.

2024-05-06 20:02 UTC, mvankeulen94 commented on source/includes/mongodump-restore-version-link.rst
> +suitable way to upgrade your deployment. To learn how to upgrade your
"a suitable" -> "the recommended"

2024-05-06 20:21 UTC, jeff-allen-mongo commented
Thanks @mvankeulen94! Made the suggested edits.

2024-05-08 19:51 UTC, mvankeulen94 approved these changes
looks great, thank you!

2024-05-08 19:54 UTC, merged