(DOCSP-40758): Clarify document order behavior for restores
mongodb/docs-commandline-tools pull request #162
Opened 2024-06-24 19:17 UTC by jeff-allen-mongo

## DESCRIPTION

Clarify document order preservation for mongodump/mongorestore and mongoexport/mongoimport.

## STAGING

- [mongodump Behavior](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-40758/mongodump/mongodump-behavior/#document-order)
- [mongorestore Behavior](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-40758/mongorestore/mongorestore-behavior-access-usage/#document-order)
- [mongoimport Behavior](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-40758/mongoimport/mongoimport-behavior/#document-order)
- [mongoexport Behavior](https://preview-mongodbjeffallenmongo.gatsbyjs.io/database-tools/DOCSP-40758/mongoexport/mongoexport-behavior/#document-order)

## JIRA

## BUILD LOG

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-06-28 15:58 UTC, tfogo requested changes

2024-06-28 15:58 UTC, tfogo commented on source/includes/mongoimport-export-document-order.rst
> +``mongoimport`` and ``mongoexport`` do not guarantee that documents
We should tell them to use `--maintainInsertionOrder`: https://www.mongodb.com/docs/database-tools/mongoimport/#std-option-mongoimport.--maintainInsertionOrder

2024-06-28 15:58 UTC, tfogo commented on source/includes/mongodump-restore-document-order.rst
> +``mongodump`` and ``mongorestore`` preserve document order during the
No, you need to set: https://www.mongodb.com/docs/database-tools/mongorestore/#std-option-mongorestore.--maintainInsertionOrder

2024-06-28 18:56 UTC, jeff-allen-mongo commented
Hi @tfogo , I updated these docs to point users to the --maintainInsertionOrder flag. I also adjusted these updates to only apply to the `mongoimport` and `mongorestore` pages. Let me know if there's any relevant info we should add to the `mongoexport` and `mongodump` pages as well.

2024-07-29 15:06 UTC, tfogo approved these changes
LGTM

2024-07-29 16:31 UTC, ianf-mongodb approved these changes
Thanks @jeff-allen-mongo, I double checked the flags are available and accurate by using `mongorestore --help` and `mongoimport --help`. This edit LGTM.

2024-07-29 16:45 UTC, merged